/** Common USCIS field offices for manual selection (not exhaustive). */
export const USCIS_FIELD_OFFICES: string[] = [
  "Atlanta GA",
  "Baltimore MD",
  "Boston MA",
  "Buffalo NY",
  "Charleston SC",
  "Chicago IL",
  "Cleveland OH",
  "Dallas TX",
  "Denver CO",
  "Detroit MI",
  "El Paso TX",
  "Fort Myers FL",
  "Harlingen TX",
  "Honolulu HI",
  "Houston TX",
  "Indianapolis IN",
  "Kansas City MO",
  "Las Vegas NV",
  "Los Angeles CA",
  "Louisville KY",
  "Manchester NH",
  "Miami FL",
  "Milwaukee WI",
  "Mount Laurel NJ",
  "Nashville TN",
  "Newark NJ",
  "New Orleans LA",
  "New York City NY",
  "Oakland CA",
  "Omaha NE",
  "Orlando FL",
  "Philadelphia PA",
  "Phoenix AZ",
  "Pittsburgh PA",
  "Portland OR",
  "Queens NY",
  "Raleigh NC",
  "Sacramento CA",
  "Saint Louis MO",
  "Saint Paul MN",
  "Salt Lake City UT",
  "San Antonio TX",
  "San Bernardino CA",
  "San Diego CA",
  "San Francisco CA",
  "San Jose CA",
  "Seattle WA",
  "Tampa FL",
  "Tucson AZ",
  "Washington DC",
].sort((a, b) => a.localeCompare(b));
